version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: 'sunday'
      time: '02:00'
      timezone: Europe/Berlin
    groups:
      dependencies:
        dependency-type: production
        patterns:
          - '*'
      dev-dependencies:
        dependency-type: development
        exclude-patterns:
          - 'puppeteer*'
          - 'chrome-devtools-frontend'
          - '@modelcontextprotocol/sdk'
          - 'yargs'
          - 'debug'
          - 'core-js'
        patterns:
          - '*'
      # breaks often so better to roll separetely.
      bundled-devtools:
        patterns:
          - 'chrome-devtools-frontend'
      bundled:
        patterns:
          - 'puppeteer*'
          - '@modelcontextprotocol/sdk'
          - 'yargs'
          - 'debug'
          - 'core-js'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: 'sunday'
      time: '04:00'
      timezone: Europe/Berlin
    groups:
      all:
        patterns:
          - '*'
